### PR TITLE
Fe pr with specs

### PR DESCRIPTION
**Pull request by andrewroth**
@twinge @jbirdjavi it's a bit of a challenge to do specs in FE because you really need some implementation holes filled in before you can test.. stuff that the enclosing app would implement.  I did a very basic implementation in spec/controllers/fe/applications_controller_spec.rb using class_eval, and it seems to work ok, but it looks a bit ugly.  Let me know if you have any ideas to make it nicer of if you think it's fine.

### CODE REVIEW

**Comment by twinge** [comment]
I thought we had found some way to do a test app under /specs that you write the specs against?

**Comment by andrewroth** [comment]
Sort of.. that app is generated on the fly and it's just a basic rails app that is set up to use the engine.  It comes from the rake task here: https://github.com/CruGlobal/qe/blob/fe/Rakefile#L12 which passes it on to the rails-dummy gem.

So unless we add our own app files that get copied over after the dummy app is created, or we somehow add the dummy app to git and add our own app files, there's no way to customize it beyond a basic app.  That's why I added some basic implementation like https://github.com/CruGlobal/qe/blob/5c75ac690ac8b14d95238d75e3e9e5e5ee683765/spec/controllers/fe/applications_controller_spec.rb#L3  The User class implemented there is a very basic User model since we actually don't have a User model in FE, yet user is assumed to exist in the enclosing app (we have Fe::User but that's different).

**Comment by twinge** [comment]
I don't see any harm in checking the dummy app into git and adding our own
files to it

**Comment by andrewroth** [comment]
@twinge I removed Fe::ApplicationsController and made sure tests still passed in panorama and sp.  I ran through submitting an app in sp to further test it still works.  I didn't test the admin part of sp, I can if you think that would be worthwhile.

**Comment by andrewroth** [comment]
Closed in favor of #13

**Pull request closed without merging**
